/* ============================================================================
   12-beyond.js — beyond the fence
   ----------------------------------------------------------------------------
   In v3 the public road, its sidewalks, the meadow verge, the markings, the
   utility corridor and all four building groups ignored siteH: at the east end
   the road hung 7.4 m above ground while its own lamps sat 9 m below it. Here
   everything reads groundH, and the road itself is generated by the phase 5
   road generator through a graded corridor.

   24 identical houses in two rows read as a diagram, so this builds five house
   types with varied setbacks, plus the grocery, clinic, school, church and park
   that b7 already names.
   ========================================================================== */

import * as THREE from 'three';
import { SITE, ELEV, LAYER, DEG, clamp, lerp, stream } from './00-config.js';
import { groundH } from './01-terrain.js';
import { MAT } from './03-materials.js';
import { place } from './02-registry.js';
import { buildBuilding } from './07-buildings.js';
import { mesh, box, cyl, decal, instanced } from './geom.js';

const r = stream('beyond');

const HOUSE_TYPES = [
  { w: 12.5, d: 9.5,  h: 3.2, storeys: 1, roof: 'gable', porch: true,  colour: 0xd8d2c4 },
  { w: 11.0, d: 11.0, h: 3.1, storeys: 1, roof: 'hip',   porch: true,  colour: 0xc8d0cc },
  { w: 10.0, d: 12.0, h: 6.0, storeys: 2, roof: 'gable', porch: false, colour: 0xbfc7bd },
  { w: 14.0, d: 8.5,  h: 3.0, storeys: 1, roof: 'shed',  porch: true,  colour: 0xd6c8b4 },
  { w: 12.0, d: 10.5, h: 5.8, storeys: 2, roof: 'hip',   porch: true,  colour: 0xcbc4bb },
];

export function buildBeyond(world, roads, pipeline) {
  const g = new THREE.Group();
  g.name = 'beyond';
  world.add(g);
  const out = { group: g, anchors: {} };

  /* ------------------------------------------------------------- housing */
  const lots = [];
  const streets = [
    { z: -880, side: -1, x0: -780, x1: 780, setback: 26 },   /* north of hood main */
    { z: -880, side: 1,  x0: -780, x1: 780, setback: 24 },   /* south of it */
    { z: -1180, side: 1, x0: -200, x1: 240, setback: 22 },
  ];
  let hi = 0;
  for (const st of streets) {
    for (let x = st.x0; x <= st.x1; x += 30) {
      /* leave gaps for the civic buildings and the park */
      if (Math.abs(x + 500) < 70) continue;
      if (Math.abs(x - 520) < 90) continue;
      if (Math.abs(x - 60) < 100 && st.side === -1) continue;
      if (Math.abs(x + 260) < 26 || Math.abs(x - 300) < 26) continue;
      const t = HOUSE_TYPES[hi % HOUSE_TYPES.length];
      const jitter = (r() - 0.5) * 7;
      const hz = st.z + st.side * (st.setback + jitter);
      lots.push({ id: 'house-' + hi, x: x + (r() - 0.5) * 4, z: hz, t,
                  rot: st.side < 0 ? Math.PI : 0, street: st, hi });
      hi++;
    }
  }

  for (const lot of lots) {
    const t = lot.t;
    place({
      id: lot.id, layer: LAYER.STRUCTURE,
      footprint: { x: lot.x, z: lot.z, w: t.w + 2, d: t.d + 2, rot: lot.rot },
      y0: groundH(lot.x, lot.z) - 1, y1: groundH(lot.x, lot.z) + t.h + 4.5,
      clearance: 3.0, parent: g, site: 'dignity village house',
      groups: ['hood'],
      build: () => house(lot, t),
    });
  }
  out.houses = lots.length;

  /* --------------------------------------------------------- civic anchors */
  const civics = [
    { id: 'grocery', x: -520, z: -940, w: 46, d: 30, h: 6.5, wall: 'panelWallW',
      label: 'Grocery', entry: 'N', service: 'S', lot: true },
    { id: 'clinic', x: 520, z: -940, w: 38, d: 26, h: 6.0, wall: 'brick',
      label: 'Clinic', entry: 'N', service: 'S', lot: true },
    { id: 'library-branch', x: 60, z: -820, w: 34, d: 22, h: 6.2, wall: 'brick',
      label: 'Library', entry: 'S', service: 'N', lot: false },
    { id: 'church', x: -140, z: -1090, w: 26, d: 34, h: 8.5, wall: 'panelWallW',
      label: 'Church', entry: 'S', service: 'N', lot: false, spire: true },
    { id: 'school', x: 520, z: -1090, w: 76, d: 34, h: 8.0, wall: 'brick',
      label: 'School', entry: 'S', service: 'N', lot: false, busLoop: true },
    { id: 'corner-store', x: -300, z: -812, w: 18, d: 14, h: 4.6, wall: 'brick',
      label: 'Corner store', entry: 'S', service: 'N', lot: false },
    /* b9: twenty-four hour childcare, co-located with the campus shift pattern */
    { id: 'childcare', x: -60, z: -1090, w: 52, d: 30, h: 6.4, wall: 'panelWallW',
      label: 'Childcare and family support', entry: 'S', service: 'N', lot: true,
      playYard: true },
    /* b5: the community water treatment plant */
    { id: 'water-plant', x: -760, z: -1120, w: 44, d: 34, h: 7.5, wall: 'panelWallD',
      label: 'Community water treatment plant', entry: 'E', service: 'W', lot: true,
      clarifiers: true },
  ];
  for (const c of civics) {
    place({
      id: c.id, layer: LAYER.STRUCTURE,
      footprint: { x: c.x, z: c.z, w: c.w, d: c.d },
      y0: groundH(c.x, c.z) - 1, y1: groundH(c.x, c.z) + c.h + (c.spire ? 16 : 3),
      clearance: 2.0, parent: g, site: c.label,
      build: () => {
        const b = buildBuilding({
          id: c.id, x: c.x, z: c.z, w: c.w, d: c.d, h: c.h,
          entryFace: c.entry, serviceFace: c.service, wall: c.wall, accent: 'precast',
          glazing: 'curtain', docks: c.lot ? 1 : 0, entries: 1, signage: true,
          roof: { pv: true, plant: true, rtu: 2, parapet: 0.9 },
        });
        if (c.spire) {
          const sy = b.roofY;
          b.group.add(mesh(box(6, 9, 6), MAT.panelWallW, c.x, sy + 4.5, c.z - c.d / 2 + 4));
          b.group.add(mesh(cyl(4.2, 0.1, 11, 4), MAT.roofSeam, c.x, sy + 14.5, c.z - c.d / 2 + 4));
          b.group.add(mesh(box(0.2, 2.4, 0.2), MAT.galv, c.x, sy + 21, c.z - c.d / 2 + 4));
          b.group.add(mesh(box(1.2, 0.2, 0.2), MAT.galv, c.x, sy + 20.6, c.z - c.d / 2 + 4));
        }
        if (c.busLoop) {
          b.group.add(decal(70, 26, c.x, c.z + 32, MAT.asphalt, 'asphalt'));
          for (let i = 0; i < 4; i++) {
            b.group.add(mesh(box(11, 3.0, 2.5), MAT.markYellow,
              c.x - 24 + i * 15, groundH(c.x, c.z + 32) + 1.6, c.z + 32));
            b.group.add(mesh(box(10.4, 1.0, 2.55), MAT.glassSimple,
              c.x - 24 + i * 15, groundH(c.x, c.z + 32) + 2.6, c.z + 32));
          }
          /* ball field and playground beside the school */
          b.group.add(decal(90, 70, c.x - 110, c.z + 20, MAT.planting, 'decal'));
        }
        if (c.playYard) {
          const py = groundH(c.x, c.z + 26);
          b.group.add(decal(46, 22, c.x, c.z + 26, MAT.rubber, 'decal'));
          for (let i = 0; i < 6; i++) {
            b.group.add(mesh(cyl(0.09, 0.09, 1.1, 8), MAT.markYellow,
              c.x - 20 + i * 8, py + 0.55, c.z + 26));
          }
          b.group.add(mesh(box(7, 0.2, 5), MAT.deck, c.x + 12, py + 1.3, c.z + 26));
          /* the yard fence: a childcare centre needs one */
          for (let i = 0; i <= 24; i++) {
            b.group.add(mesh(cyl(0.05, 0.05, 1.3, 6), MAT.galv,
              c.x - 24 + i * 2, py + 0.65, c.z + 37));
          }
        }
        if (c.clarifiers) {
          const wy = groundH(c.x, c.z);
          /* two circular clarifiers with rotating bridges, plus filter beds */
          for (let i = 0; i < 2; i++) {
            const cx2 = c.x + 34 + i * 30, cz2 = c.z + 4;
            const gy = groundH(cx2, cz2);
            b.group.add(mesh(cyl(13, 13.4, 3.6, 32), MAT.precast, cx2, gy + 1.6, cz2));
            b.group.add(mesh(cyl(12.2, 12.2, 0.12, 32), MAT.glassSimple, cx2, gy + 2.9, cz2));
            b.group.add(mesh(box(26, 0.5, 1.1), MAT.galv, cx2, gy + 3.7, cz2));
            b.group.add(mesh(cyl(1.6, 1.6, 4.4, 16), MAT.precast, cx2, gy + 2.0, cz2));
          }
          for (let i = 0; i < 4; i++) {
            b.group.add(mesh(box(16, 1.6, 7), MAT.precast,
              c.x + 20 + i * 18, wy + 0.8, c.z - 30));
          }
          b.group.add(mesh(cyl(4.2, 4.2, 11, 20), MAT.galv, c.x - 30, wy + 5.5, c.z - 8));
        }
        return b.group;
      },
    });
    out.anchors[c.id] = [c.x, groundH(c.x, c.z) + c.h + 2, c.z];
  }

  /* -------------------------------------------------------------- the park */
  {
    const px = 60, pz = -1060;
    place({
      id: 'hood-park', layer: LAYER.PROP,
      footprint: { x: px, z: pz, w: 170, d: 110 },
      y0: groundH(px, pz) - 0.4, y1: groundH(px, pz) + 7,
      parent: g, site: 'neighbourhood park',
      build: () => {
        const grp = new THREE.Group();
        const py = groundH(px, pz);
        /* ball field: backstop, base paths, outfield */
        grp.add(decal(90, 90, px + 34, pz, MAT.planting, 'decal'));
        for (let i = 0; i < 9; i++) {
          const a = Math.PI * 0.25 + (i / 8) * Math.PI * 0.5;
          grp.add(mesh(box(0.08, 5.5, 0.08), MAT.galv,
            px + 4 + Math.cos(a) * 9, py + 2.75, pz + Math.sin(a) * 9));
        }
        /* playground: structure, swings, safety surface */
        grp.add(decal(34, 26, px - 52, pz + 12, MAT.rubber, 'decal'));
        for (let i = 0; i < 4; i++) {
          grp.add(mesh(cyl(0.12, 0.12, 3.4, 8), MAT.markYellow,
            px - 60 + (i % 2) * 8, py + 1.7, pz + 6 + Math.floor(i / 2) * 8));
        }
        grp.add(mesh(box(9, 0.25, 9), MAT.deck, px - 56, py + 2.4, pz + 10));
        grp.add(mesh(box(0.16, 0.16, 8), MAT.galv, px - 40, py + 3.2, pz + 14));
        for (const s of [-1, 1]) {
          grp.add(mesh(cyl(0.10, 0.10, 3.4, 8), MAT.galv, px - 40 + s * 0.1, py + 1.7, pz + 14 + s * 4));
          grp.add(mesh(box(0.5, 0.06, 0.24), MAT.rubber, px - 40 + s * 1.6, py + 0.6, pz + 14));
        }
        /* picnic shelters */
        for (let i = 0; i < 2; i++) {
          const sx = px - 20 + i * 26, sz = pz - 34;
          for (const ax of [-1, 1]) for (const az of [-1, 1]) {
            grp.add(mesh(box(0.2, 2.8, 0.2), MAT.deck, sx + ax * 3.4, py + 1.4, sz + az * 3.4));
          }
          grp.add(mesh(cyl(5.6, 0.1, 1.6, 4), MAT.roofSeam, sx, py + 3.6, sz, { rotY: Math.PI / 4 }));
          grp.add(mesh(box(4, 0.1, 1.2), MAT.deck, sx, py + 0.75, sz));
        }
        return grp;
      },
    });
  }

  /* --------------------------------------------- microtransit stops (b7) */
  const stops = [
    ['transit-campus', -18, -672], ['transit-grocery', -520, -906],
    ['transit-clinic', 520, -906], ['transit-library', 60, -846],
    ['transit-school', 520, -1054],
  ];
  for (const [id, sx, sz] of stops) {
    place({
      id, layer: LAYER.PROP,
      footprint: { x: sx, z: sz, w: 6.5, d: 3.4 },
      y0: groundH(sx, sz) - 0.3, y1: groundH(sx, sz) + 3.6,
      parent: g, site: 'microtransit shelter',
      build: () => {
        const grp = new THREE.Group();
        const sy = groundH(sx, sz);
        grp.add(decal(9, 5, sx, sz, MAT.concretePad, 'pavementEdge'));
        for (const ax of [-1, 1]) {
          grp.add(mesh(box(0.14, 2.7, 0.14), MAT.steelDark, sx + ax * 3.0, sy + 1.35, sz + 1.4));
          grp.add(mesh(box(0.14, 2.7, 0.14), MAT.steelDark, sx + ax * 3.0, sy + 1.35, sz - 1.4));
        }
        grp.add(mesh(box(7.0, 0.14, 3.6), MAT.alu, sx, sy + 2.8, sz));
        const back = new THREE.Mesh(new THREE.PlaneGeometry(6.4, 2.2), MAT.glassSimple);
        back.position.set(sx, sy + 1.5, sz - 1.5);
        grp.add(back);
        grp.add(mesh(box(5.4, 0.10, 0.45), MAT.deck, sx, sy + 0.55, sz - 0.9));
        grp.add(mesh(box(0.9, 0.6, 0.05), MAT.emitCool, sx + 2.4, sy + 1.9, sz - 1.42));
        /* rooftop PV powering the shelter light */
        grp.add(mesh(box(2.4, 0.05, 1.4), MAT.pv, sx - 1.8, sy + 2.92, sz));
        return grp;
      },
    });
  }

  /* ------------------------------------------- water kiosks (b5) and vaults */
  for (let i = 0; i < 4; i++) {
    const kx = -600 + i * 400, kz = -830;
    place({
      id: 'water-kiosk-' + i, layer: LAYER.PROP,
      footprint: { x: kx, z: kz, w: 3.2, d: 2.4 },
      y0: groundH(kx, kz) - 0.3, y1: groundH(kx, kz) + 3.0,
      parent: g, site: 'community water kiosk',
      build: () => {
        const grp = new THREE.Group();
        const ky = groundH(kx, kz);
        grp.add(decal(5, 4, kx, kz, MAT.concretePad, 'pavementEdge'));
        grp.add(mesh(box(2.6, 2.3, 1.7), MAT.panelWallW, kx, ky + 1.15, kz));
        grp.add(mesh(box(3.0, 0.16, 2.1), MAT.roofSeam, kx, ky + 2.35, kz));
        grp.add(mesh(box(2.2, 0.05, 1.3), MAT.pv, kx, ky + 2.48, kz));
        grp.add(mesh(box(0.7, 0.5, 0.06), MAT.emitCool, kx, ky + 1.5, kz + 0.88));
        for (const s of [-1, 1]) {
          grp.add(mesh(cyl(0.04, 0.04, 0.35, 6), MAT.alu, kx + s * 0.7, ky + 1.05, kz + 0.92, { rotX: 1.2 }));
        }
        return grp;
      },
    });
  }

  /* underground utility corridor with vaults, pedestals and a trench in
     progress — stated feature b8 */
  place({
    id: 'utility-corridor', layer: LAYER.UTILITY,
    footprint: { x: 0, z: -800, w: 1580, d: 4 },
    y0: groundH(0, -800) - 2, y1: groundH(0, -800) + 1.6,
    parent: g, site: 'underground utility corridor',
    allowOverlapWith: ['road', 'walk', 'apron', 'hood'],
    tags: ['no-geom-audit'],
    build: () => {
      const grp = new THREE.Group();
      for (let x = -780; x <= 780; x += 60) {
        const y = groundH(x, -800);
        grp.add(mesh(box(1.8, 0.12, 1.2), MAT.concretePad, x, y + ELEV.decal, -800, { cast: false }));
        grp.add(mesh(box(0.5, 1.1, 0.35), MAT.panelWallW, x + 3, y + 0.55, -800));
      }
      /* the open trench vignette */
      const tx = 180;
      for (let i = 0; i < 22; i++) {
        const px = tx + i * 2.4;
        grp.add(mesh(box(2.4, 1.4, 2.2), MAT.dirt, px, groundH(px, -800) - 0.7, -800, { cast: false }));
        grp.add(mesh(cyl(0.16, 0.16, 2.4, 8), MAT.markYellow, px, groundH(px, -800) - 1.1, -800,
          { rotZ: Math.PI / 2 }));
      }
      for (let i = 0; i <= 24; i++) {
        const px = tx - 2 + i * 2.4;
        grp.add(mesh(cyl(0.03, 0.03, 1.1, 5), MAT.markRed, px, groundH(px, -800) + 0.55, -797));
      }
      grp.add(mesh(box(58, 1.0, 3.0), MAT.dirt, tx + 26, groundH(tx + 26, -804) + 0.5, -804.5, { cast: true }));
      return grp;
    },
  });

  return out;
}

/* ------------------------------------------------------------------- house */
function house(lot, t) {
  const grp = new THREE.Group();
  const x = lot.x, z = lot.z, rot = lot.rot;
  const y = groundH(x, z);
  const hw = t.w / 2, hd = t.d / 2;
  const H = t.h * (t.storeys === 2 ? 1 : 1);

  grp.add(decal(t.w + 4, t.d + 4, x, z, MAT.planting, 'decal', rot));
  grp.add(mesh(box(t.w + 0.5, 0.6, t.d + 0.5), MAT.precast, x, y + 0.3, z, { rotY: rot }));
  const body = mesh(box(t.w, H, t.d), MAT.panelWallW, x, y + 0.6 + H / 2, z, { rotY: rot });
  body.material = MAT.panelWallW;
  grp.add(body);

  /* roof */
  const ry = y + 0.6 + H;
  if (t.roof === 'gable') {
    const shape = new THREE.Shape();
    shape.moveTo(-hd - 0.5, 0); shape.lineTo(hd + 0.5, 0); shape.lineTo(0, 2.9);
    const g2 = new THREE.ExtrudeGeometry(shape, { depth: t.w + 1.0, bevelEnabled: false });
    g2.rotateY(Math.PI / 2);
    g2.translate(x - (t.w + 1.0) / 2 * Math.cos(rot), ry, z);
    const m = new THREE.Mesh(g2, MAT.roofSeam);
    m.castShadow = true; m.receiveShadow = true;
    m.position.set(0, 0, 0);
    grp.add(m);
  } else if (t.roof === 'hip') {
    grp.add(mesh(new THREE.ConeGeometry(Math.max(hw, hd) * 1.28, 2.6, 4), MAT.roofSeam,
      x, ry + 1.3, z, { rotY: rot + Math.PI / 4 }));
  } else {
    const m = mesh(box(t.w + 1.0, 0.28, t.d + 1.0), MAT.roofSeam, x, ry + 0.9, z, { rotY: rot });
    m.rotation.z = 0.14;
    grp.add(m);
  }

  /* porch */
  if (t.porch) {
    const px = x, pz = z + (rot === 0 ? hd + 1.6 : -hd - 1.6);
    grp.add(mesh(box(t.w * 0.72, 0.32, 3.0), MAT.deck, px, y + 0.62, pz, { rotY: rot }));
    for (let i = 0; i < 3; i++) {
      const cx = px - t.w * 0.28 + i * t.w * 0.28;
      grp.add(mesh(box(0.16, 2.6, 0.16), MAT.deck, cx, y + 2.0, pz + (rot === 0 ? 1.3 : -1.3)));
    }
    grp.add(mesh(box(t.w * 0.76, 0.16, 3.4), MAT.roofSeam, px, y + 3.4, pz, { rotY: rot }));
  }

  /* windows and a door */
  const fz = z + (rot === 0 ? hd + 0.04 : -hd - 0.04);
  for (let i = 0; i < 3; i++) {
    const wx = x - t.w * 0.3 + i * t.w * 0.3;
    const pane = new THREE.Mesh(new THREE.PlaneGeometry(1.15, 1.35), MAT.glass);
    pane.position.set(wx, y + 2.1, fz);
    pane.rotation.y = rot;
    grp.add(pane);
    grp.add(mesh(box(1.45, 1.62, 0.10), MAT.precast, wx, y + 2.1, fz - (rot === 0 ? 0.06 : -0.06), { rotY: rot }));
  }
  grp.add(mesh(box(1.0, 2.1, 0.10), MAT.deck, x + t.w * 0.34, y + 1.65, fz, { rotY: rot }));
  if (t.storeys === 2) {
    for (let i = 0; i < 2; i++) {
      const wx = x - t.w * 0.22 + i * t.w * 0.44;
      const pane = new THREE.Mesh(new THREE.PlaneGeometry(1.05, 1.25), MAT.glass);
      pane.position.set(wx, y + 4.9, fz);
      pane.rotation.y = rot;
      grp.add(pane);
    }
  }

  /* home solar and a wall-mounted battery — the 300-home program, b6 */
  const pv = [];
  const rows = t.roof === 'shed' ? 3 : 2;
  for (let i = 0; i < rows; i++) {
    for (let j = 0; j < 4; j++) {
      pv.push({ x: x - t.w * 0.3 + j * (t.w * 0.2), y: ry + 1.55 + i * 0.06,
                z: z - t.d * 0.2 + i * (t.d * 0.24), rx: -0.42, ry: rot, s: 1 });
    }
  }
  grp.add(instanced(new THREE.BoxGeometry(1.6, 0.04, 1.0), MAT.pv, pv, { cast: true, receive: false }));
  grp.add(mesh(box(0.7, 1.1, 0.24), MAT.panelWallW, x - hw - 0.14, y + 1.5, z - hd * 0.4, { rotY: rot }));
  grp.add(mesh(box(0.34, 0.24, 0.03), MAT.emitCool, x - hw - 0.28, y + 1.9, z - hd * 0.4, { rotY: rot }));

  /* driveway, mailbox, yard tree pit and a fence line */
  const dz = lot.street.z + lot.street.side * 12;
  grp.add(decal(3.4, Math.abs(dz - z) + 6, x - t.w * 0.3, (z + dz) / 2, MAT.asphaltWorn, 'asphalt'));
  const mz = lot.street.z + lot.street.side * 9;
  grp.add(mesh(cyl(0.06, 0.06, 1.2, 6), MAT.deck, x - t.w * 0.3 + 2.4, groundH(x, mz) + 0.6, mz));
  grp.add(mesh(box(0.5, 0.24, 0.24), MAT.galv, x - t.w * 0.3 + 2.4, groundH(x, mz) + 1.3, mz));
  if (r() > 0.55) {
    grp.add(mesh(box(3.0, 2.3, 2.6), MAT.deck, x + hw - 1.6, y + 1.15, z - hd - 2.6, { rotY: rot }));
    grp.add(mesh(box(3.3, 0.18, 2.9), MAT.roofSeam, y ? x + hw - 1.6 : 0, y + 2.4, z - hd - 2.6, { rotY: rot }));
  }
  return grp;
}
